operating system name (\$OS) ............. [$OS]
operating system version (\$OSVER) ....... [$OSVER]
operating system class (\$OSCLASS) ....... [$OSCLASS]

current code level (\$CODELEVEL) ......... [$CODELEVEL]

tmk script ..................... [$::tmk::scriptName]
tmk directory .................. [$::tmk::dir]

user's config cache directory .. [$::tmk::cacheDir]
cache file for this system ..... [$cacheFile]

note: you can regenerate the config cache using 'tmk -reconfig'
